### ISSUE TITLE
All requests fail when using Siege

### ISSUE THREAD

**Issue by chmike** [jorisvink/kore#122]
I'm doing some simple benchmarking of kore with Siege, but I get abnormally low number of hits. When I use https://github.com/wg/wrk I get excellent number of transactions per second. 

I used the very latest version of kore. The page function is as follow:
int
page(struct http_request *req)
{
        http_response(req, 200, "Hello world", 11);
        return (KORE_RESULT_OK);
}

The configuration is as follow:
bind            127.0.0.1 8080
load            ./kore2.so
workers                         4
worker_max_connections          250
worker_rlimit_nofiles           1024
worker_accept_threshold         10
domain 127.0.0.1 {
        static  /       page
}

I used make NOTLS=1 to build kore.

Another benchmark showing a weird result with kore and siege is here http://forum.dlang.org/post/zuvwojstoepatsqczctb@forum.dlang.org

Is there an explanation for this ?

**Comment by jorisvink** [comment]
Hi,

Interesting.

What kind of numbers do you get with siege if you run for 30 seconds? About 2043 transactions?

.joris

**Comment by jorisvink** [comment]
Ok so this is related to the way Kore actually spreads out incoming connections.

The kore worker processes have what you would call an “accept lock”. If a worker holds this lock it will be listening on the accepting socket for new connections. Only one worker may hold this lock at a time. This prevents a thundering herd problem in case you have a large number of worker processes.

Whenever the worker that holds the lock starts accepting new connections via accept() it will do so until either worker_accept_threshold is reached or until it reaches its worker_max_connections setting. After this a worker will relinquish the lock so it is up for grabs by another worker. (The idea behind this being: if you just accepted a large number of connections you’re going to be busy dealing with them).

After the worker has relinquished the accept lock it will back off for 500 milliseconds until it will actively attempt to grab said lock again from other workers. (again, due to the fact you just accepted a bunch of connections and you may be busy).

This is exactly what you are seeing with siege. In the use case listed on the forum you linked are running siege with a concurrency of 20. In siege its case this means: connect 20 times in one go, perform the requests and disconnect.

So looking at that from Kore’s point of view and your configuration with the siege benchmark tool, a worker accepts 10 connections in a single go and then relinquishes the lock. In the first 40 connections all workers will pick them up rather fast. But after that they are being throttled by the 500 ms delay before they will start accepting new connections even though they clearly aren’t very busy.

If you rerun the siege tool against a single worker you will probably see better results.

Hope this sheds some light on things.

**Comment by chmike** [comment]
Thank you very much. So the reason is this 500ms pause? Can this delay be adjusted ? Why is there such pause ? Why is the ˋwrk` benchmarking tool not affected by this pause ?

The hello world example is not realistic, but I could use kore for a web service using cached data so that serving the request could be as fast as the hello world example. How can I avoid being penalized by the 500ms pause ?

**Comment by jorisvink** [comment]
> Can this delay be adjusted?

Not at runtime. It's a define in worker.c (WORKER_LOCK_TIMEOUT).

> Why is there such pause?

As I stated before the pause is there due to the workers having accepted new connections and wanting to deal with them first. Under low pressure this is very noticeable (as with siege). Under high pressure you cannot notice this.

> Why is the wrk benchmarking tool not affected by this pause?

Because wrk and siege behave differently in their "concurrent connections". Also wrk seems to produce way more pressure then siege does. Not that I am an expert on either.

> How can I avoid being penalized by the 500ms pause?

You won't in real life.

**Comment by jorisvink** [comment]
@chmike Any more questions regarding this topic?
