### ISSUE TITLE
ERR_SSL_VERSION_OR_CIPHER_MISMATCH trying to connect to kore written website

### ISSUE THREAD

**Issue by raphaelmonrouzeau** [jorisvink/kore#128]
Chrome on my Mac now refuses to connect to my web service written with Kore because of the following:
```
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

Unsupported protocol
The client and server don't support a common SSL protocol version or cipher suite.
This is likely to be caused when the server needs RC4, which is no longer considered secure.
```

I tried to clean / rebuild and update my kore install already. Should I regenerate dh2048.pem ?

**Comment by jorisvink** [comment]
What kind of cert are you using?

Also I may have been a bit overzealous with the SNI changes, can you try revision f62430d1fadad06b35bd0dcd7e0cc2b0768c7d44 instead of HEAD?

.joris

**Comment by jorisvink** [comment]
I just reverted that commit as it was indeed breaking things more then I recognised earlier.

**Comment by jorisvink** [comment]
Please confirm if this fixes the issue you were having.

**Comment by raphaelmonrouzeau** [comment]
I confirm I can now access the site using the IP (127.0.0.1).

I still can't access it using hostname (localhost) even if CN=localhost in the auto-generated server.crt.

At least I can access it, if there is settings outside making your certificate in Kore, I would love to have a pointer to where I can document myself about them. I'd be happy to test and learn how to use Kore outside development settings :)

**Comment by jorisvink** [comment]
Ok.

You probably cannot "reach" it under localhost since the default domain configuration lists 127.0.0.1 as the hostname rather then localhost. (see your configuration).

The domain directives are matched to the "Host" sent by your browser in order for Kore to figure out what page handlers to check and what not. It is also used for SNI TLS extension so it can map the proper certificate and keys towards it.

**Comment by jorisvink** [comment]
Since your bug is resolved I will be closing this issue now.
