### ISSUE TITLE
Other SQL backends?

### ISSUE THREAD

**Issue by ryu0** [jorisvink/kore#181]
Would you be willing to accept other SQL implementations for the framework APIs, such as sqlite?

**Comment by jorisvink** [comment]
> On Mar 9, 2017, at 17:54, James Buren <notifications@github.com> wrote:
> 
> Would you be willing to accept other SQL implementations for the framework APIs, such as sqlite?
> 

Hmm, maybe. The reason why Kore has a pgsql backend was to tie the asynchronous methods to http requests in a sensible way.

I'm not familiar with other ones, but if their C API does not support asynchronous queries there may not be any need to abstract that away into kore.

.joris

**Comment by strangepete** [comment]
Sqlite only supports async via a module; but its fast as heck normally, only runs locally & single-user and shouldn't need to be async.

Since the pgsql functions are fairly generic already, it would be _nice_ if you could specify a different underlying engine - ideally defaulted in code, and overridden in conf - and just have implementation issues sussed out within the engine interface functions (i.e., an sqlite interface would revert to KORE_SYNC and give a warning; a mysql interface would set it's equivalent flags, etc...) And allow a module to easily add its own interface if something custom/funky is needed.

Less complex the better, obviously; a dev could target more DBs by simply writing more portable SQL statements. Simplicity probably goes out the tubes if you want to use prepared statements in the future...

Just a couple thoughts

**Comment by jorisvink** [comment]
> Sqlite only supports async via a module; but its fast as heck normally, only runs locally & single-user and shouldn't need to be async.
> 
Yes, I'm aware.
> Since the pgsql functions are fairly generic already, it would be nice if you could specify a different underlying engine - ideally defaulted in code, and overridden in conf - and just have implementation issues sussed out within the engine interface functions (i.e., an sqlite interface would revert to KORE_SYNC and give a warning; a mysql interface would set it's equivalent flags, etc...) And allow a module to easily add its own interface if something custom/funky is needed.
> 
While I'm not 100% convinced this it worth the time if someone provides a decent PR that does this I may reconsider if it's done right.

What's the right way? I currently don't know.


.joris

**Comment by strangepete** [comment]
> Yes, I'm aware.

Pardon, I had misread your post

> What's the right way? I currently don't know.

After reading around for a fairly short bit (telling) it looks like the right way probably is to continue as-is: even with portable sql, all the other differences are a nightmare. I guess my post was sleepy wishful thinking, disregard!
