### ISSUE TITLE
Provide API for embedding Kore into an application

### ISSUE THREAD

**Issue by kiwidrew** [jorisvink/kore#2]
I'm currently using libmicrohttpd for a project of mine, but have a growing distaste for its API, which goes to great lengths to avoid making any memory allocations.  What are the plans for providing an embedding API for Kore?  (To be specific, that means the ability to programmatically configure, start and stop a Kore server instance, with no need to write configuration files.)

**Comment by alexreg** [comment]
I'm not familiar with the architecture of Kore yet, but what problems specifically do you envisage with making it available as a library/API?

I'm not sure how alternative web application frameworks like [Mongoose](https://code.google.com/p/mongoose/) and [Onion](http://www.coralbits.com/libonion/) do it, but it may be worth taking a look...

(Sorry if I'm rather misinformed about your aims here!)

**Comment by jorisvink** [comment]
Kore loads your stuff as a dynamic library so you can on-the-fly reload said library while still serving content. This is the biggest headache with turning Kore itself into a "library to link against".

Others do it because that is probably their goal and how they built it, however I disagree with that approach for Kore as I see Kore more of a platform that hosts your code rather then a library that you link against.

**Comment by alexreg** [comment]
Yeah, I see your aim I think... Kore is not only a web application framework, but the server itself really, isn't it? Personally, my intention to use Kore for hosting a website, so I don't need the library functionality right now, though I can envisage it being useful still.

What if the Kore library were just a high level API akin to the CLI (command-line interface)? Not exactly the same of course, but similar at least. So there would be functions corresponding to the available CLI commands or options, with appropriate parameters. Then you could just add in some event handlers / hooks corresponding to connections opening, closed, and requests & responses being sent/received. Plus maybe some global variables for things like a list of open/active connections, and statistics on data received/served to clients.

(Incidentally I think the CLI is a bit confusing as it is – probably better to do everything in term of commands, or better still everything in terms of options – I recommend [argp](https://github.com/alexreg/libargp) to handle the CLI.)

**Comment by jorisvink** [comment]
Correct.

Having spent my evening reasoning on this topic, I no longer see any valid arguments for Kore to become a library though or to add a bunch of code to make it possible in the first place (which in place would mean losing on-the-fly reloads of your code and potentially tons of other problems).

**Comment by alexreg** [comment]
Aha. Would you really lose on-the-fly reloads though? Surely one dynamic library can load/unload another dynamic library, through the usual `dlopen`/`dlclose` functions?

The alternative of course is just making the non-low-level side of Kore (protocol handling, page handlers, caching, background tasks, events, etc.) available as a library (which would be minimal new code in theory), so that the library can be integrated into other servers that do more than 'just' HTTP. Of course, I understand Kore is meant to be a fully-fledged web application server in its own right.

Anyway, that's just my take on things. The final decision is naturally yours, and I will continue using Kore in either case. :)

**Comment by jorisvink** [comment]
> Aha. Would you really lose on-the-fly reloads though? Surely one dynamic library can load/unload another dynamic library, through the usual dlopen/dlclose functions?

Sure but then what? dlopen your other binary you build which was linked against Kore .. and then what?

No, having Kore as a linkable library does not work =)

**Comment by jorisvink** [comment]
Closing this issue now :)

**Comment by alexreg** [comment]
Okay, fair enough. I understand your perspective here. :)

**Comment by alexreg** [comment]
Final little question, if you don’t mind… do you intend to make Kore suitable and reliable enough for use in a production environment? Will this include the capability to run Kore as a system daemon, with a configuration file perhaps?

Cheers.

**Comment by jorisvink** [comment]
Kore is more then suitable for production use.

The command line tools are only useful when hacking on your code really, doing a kore -h will show you some options to start Kore in the background.

More specifically:

```
# kore -c conf/myconf.conf
```

This starts kore daemonized with everything going to syslog, a pid file is written (via config can be configured where) so you can always send a SIGHUP to reload your module or SIGQUIT to gracefully shutdown Kore.

See https://github.com/jorisvink/kore/blob/master/conf/kore.conf.example for a full example of all available configuration options.

**Comment by alexreg** [comment]
Excellent. Thanks for confirming these things.
