### ISSUE TITLE
Large file upload support

### ISSUE THREAD

**Issue by shivshankardayal** [jorisvink/kore#230]
How big file can be uploaded via kore.io? Is it async in nature?

**Comment by jorisvink** [comment]
You can control the size of incoming HTTP bodies via the configuration option 'http_body_max'.

Additionally if you want really large uploads I recommend you use disk offloading which is controlled via the 'http_body_disk_offload' configuration option. Any incoming body larger than this gets offloaded to disk rather than an in-memory buffer.

Yes it is asynchronous in nature in the sense that any incoming bodies are read while also still dealing with other connected clients. Your page handlers are not called until the entire HTTP header and any additional incoming HTTP body is read.

**Comment by shivshankardayal** [comment]
Thanks.
