### ISSUE TITLE
I try to make the project but with the error occur...

### ISSUE THREAD

**Issue by jikaigit** [jorisvink/kore#45]
cc -Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wsign-compare -Iincludes -g -DPREFIX='"/usr/local"' -D_GNU_SOURCE=1 -c src/kore.c -o src/kore.o
In file included from src/kore.c:22:0:
includes/kore.h:30:25: fatal error: openssl/err.h: 没有那个文件或目录
 #include <openssl/err.h>
                         ^
compilation terminated.
make: *** [src/kore.o] 错误 1

All dependences about openssl  can not found in your project....Maybe you can add the file about openssl in your source directory on the github~

**Comment by jorisvink** [comment]
Hi.

Is openssl installed on your system?

> All dependences about openssl can not found in your project

Because this dependancy usually is available on your system. If its not I recommend you either install or from which ever package repository you have available on the system you are using or grab the latest openssl build it and install it on your system. The former seems easier however.

.joris

**Comment by jikaigit** [comment]
I am a fresh man about Linux. But I think my linux has installed openssl because I can use openssl command in the terminal....

When I want to make the kore project, it reports that some file of openssl can not found

**Comment by jorisvink** [comment]
You probably have openssl binaries but not the required headers for development.

See if you can install libssl-dev or equivalent.

**Comment by jikaigit** [comment]
The problem is dealt. Thanks for author
