### ISSUE TITLE
Does it support routes like Flask?

### ISSUE THREAD

**Issue by tfarina** [jorisvink/kore#73]

**Comment by Geenz** [comment]
AFAIK, right now you can only really define routes via the configuration file.  What's the usecase for having routes defined at runtime?

**Comment by jorisvink** [comment]
I'm unfamiliar with routes in flask. So you'll have to provide a better description for what the problem is. :-)

**Comment by Geenz** [comment]
@jorisvink Basically, instead of defining page handlers for an application (i.e., "/upload") in a configuration file, you do it in-line with your application's code.

You would instead do something like: ```app.route("/upload");```

It's become a popular way to setup web apps due to its convenience, but achieves the same effect that Kore's page handlers within the app's config file does.

**Comment by tfarina** [comment]
Ah! In Kore you do in plain config files (they look very similar to the nginx ones)!

https://github.com/jorisvink/kore/blob/master/examples/generic/conf/generic.conf

So,

static / serve_index

Would be the equivalent to Flask's 
@app.route('/')

**Comment by Geenz** [comment]
@tfarina That is correct.
